locallibrary/catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index, name='index'),
]

urlpatterns = [
    path('', views.index, name='index'),
    path('cards/', views.CardListView.as_view(), name='cards'),
]

urlpatterns += [
    path('', views.index, name='index'),
    path('cards/', views.CardListView.as_view(), name='cards'),
    path('card/<int:pk>', views.CardDetailView.as_view(), name='card-detail'),
]


urlpatterns += [

    path('atm/<int:pk>', views.ATMDetailView.as_view(), name='atm-detail'),
]




urlpatterns += [
    path('card/<int:pk>/transfer/', views.transfer_card_user, name='transfer-card-user'),
]

urlpatterns += [
    path('withdraw/', views.WithdrawTransactionView, name='withdraw'),
]

urlpatterns += [
    path('transfer/', views.TransferTransactionView, name='transfer'),
]

urlpatterns += [
    path('balance/', views.BalanceInqView.as_view(), name='balance'),
]

urlpatterns += [
    path('', views.index, name='index'),
    path('accounts/', views.CardListView.as_view(), name='accounts'),
    path('accounts/<int:pk>', views.AccountDetailView.as_view(), name='account-detail'),
]


urlpatterns += [
    path('mycards/', views.LoanedBooksByUserListView.as_view(), name='my-cards'),
]

urlpatterns += [
    path('atms/', views.ATMListView.as_view(), name='atms'),

]

urlpatterns += [
    path('create_account/', views.UserCreateAccountView, name='create-account'),

]


urlpatterns += [
    path('admin_create_account/', views.AdminCreateAccountView, name='admin-create-account'),

]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User


# Create your models here.


class Account(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    name = models.CharField(max_length=100, null=False,default="Test")
    account_number = models.IntegerField(unique=True, primary_key=True)
    #email = models.CharField(max_length=100, null=False,default="test@gmail.com")
    #password = models.CharField(max_length=100, null=False,default="Test123!")
    pin = models.IntegerField()
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    balance = models.IntegerField(null=False, default = 0)
    bank_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    


    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('account-detail', args=[str(self.id)])
        
        

class Card(models.Model):
    owner = models.CharField(max_length=100, null=False,default="Test")
    date_issued = models.DateField(null=True)
    date_expires = models.DateField(null=True)
    #balance = models.IntegerField()
    account = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    

    
    def __str__(self):
        """String for representing the Model object."""
        return self.owner

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('card-detail', args=[str(self.id)])
        
        
import uuid

class ATM(models.Model):
    atm_number = models.IntegerField(unique= True, null=False, primary_key=True)
    address = models.CharField(max_length=100, null=False,default="Test Location")
    status = models.CharField(max_length=100, null=False,default="Available")
    last_refill = models.DateField(null=True)
    next_refill = models.DateField(null=True)
    min_balance = models.IntegerField(default = 0)
    current_balance = models.IntegerField(default=100)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.address

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('atm-detail', args=[str(self.atm_number)])
	
	
        
        
  

locallibrary/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from catalog.models import Account, Card, ATM

class RenewBookForm(forms.Form):
    transfer_amount = forms.IntegerField(help_text="Enter an amount to transfer.")
    def clean_transfer_amount(self):
    	data = self.cleaned_data['transfer_amount']
    	if data < 0:
    		raise ValidationError(_('Invalid amount.'))
    	return data


class WithdrawTransactionForm(forms.Form):
    amount = forms.IntegerField(min_value=1)
    account = forms.ModelChoiceField(queryset=Account.objects.all())
    atm = forms.ModelChoiceField(queryset=ATM.objects.all())

    def __init__(self, user, *args, **kwargs):
        super(WithdrawTransactionForm, self).__init__(*args, **kwargs)
        self.fields['account'].queryset = Account.objects.filter(bank_user=user)
        self.redirect = False

    def withdraw_amount(self):
        amount = self.cleaned_data['amount']
        account = self.cleaned_data['account']
        atm = self.cleaned_data['atm']

        if amount > account.balance:
            self.redirect = True
            return 1
        elif amount > (atm.current_balance - atm.min_balance):
            self.redirect = True
            return -1
        else:
            account.balance -= amount
            account.save()
            atm.current_balance -= amount
            atm.save()
        return amount
        
class TransferTransactionForm(forms.Form):
    amount = forms.IntegerField(min_value=1)
    from_account = forms.ModelChoiceField(queryset=Account.objects.all())
    to_account = forms.ModelChoiceField(queryset=Account.objects.all())
    def __init__(self, user, *args, **kwargs):
        super(TransferTransactionForm, self).__init__(*args, **kwargs)
        self.fields['from_account'].queryset = Account.objects.filter(bank_user=user)
        self.fields['to_account'].queryset = Account.objects.all()
        self.redirect = False
            
    def transfer_amount(self):
        amount = self.cleaned_data['amount']
        from_account = self.cleaned_data['from_account']
        to_account = self.cleaned_data['to_account']
        if amount > from_account.balance:
            self.redirect = True
            return 1
        else:
            from_account.balance -= amount
            from_account.save()
            to_account.balance += amount
            to_account.save()
        return amount

class UserAccountCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')
        
class AdminAccountCreationForm(ModelForm):
    class Meta:
        model = Account
        fields = ('name', 'account_number', 'pin', 'address', 'balance', 'phone_number', 'bank_user')

locallibrary/catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User


# Create your views here.

from .models import Card, Account, ATM

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_cards = Card.objects.all().count()
    num_accounts = Account.objects.all().count()
    

 # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1



    context = {
        'num_cards': num_cards,
        'num_accounts': num_accounts,
  
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)
    
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin

class CardListView(generic.ListView):
    model = Card
    context_object_name = 'my_card_list'   # your own name for the list as a template variable
    queryset = Card.objects # Get 5 books containing the title war
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location


class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = Card
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    def get_queryset(self):
        return Card.objects.filter(account=self.request.user)
        
class CardDetailView(generic.DetailView):
    model = Card
    
class AccountDetailView(generic.DetailView):
    model = Account    

class ATMDetailView(generic.DetailView):
    model = ATM

    
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewBookForm, WithdrawTransactionForm, TransferTransactionForm, UserAccountCreationForm, AdminAccountCreationForm

@login_required
#@permission_required('catalog.can_mark_returned', raise_exception=True)
def transfer_card_user(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    card_instance = get_object_or_404(Card, pk=pk)
    # If this is a POST request then process the Form data
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            card_instance = form.cleaned_data['transfer_amount']
            card_instance.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('my-borrowed') )
    # If this is a GET (or any other method) create the default form.
    else:
        proposed_transfer_amount = 5
        form = RenewBookForm(initial={'transfer_amount': proposed_transfer})
    context = {
        'form': form,
        'card_instance': card_instance,
    }
    return render(request, 'catalog/transfer_card_user.html', context)
    
@login_required
def WithdrawTransactionView(request):
    if request.method == "POST":
        form = WithdrawTransactionForm(request.user, request.POST)
        if form.is_valid():
            response_code = form.withdraw_amount()
            if form.redirect:
                if response_code == 1:
                #not enough money in account
                    print("MONEY ERROR")
                    return HttpResponseRedirect(reverse('my-cards') )
                elif response_code == -1:
                #not enough money in atm
                    print("ATM ERORR")
                    return HttpResponseRedirect(reverse('my-details') )
            else:
                print("Success")
                return HttpResponseRedirect(reverse('index') )

    form = WithdrawTransactionForm(request.user)
    context = {
         'form' : form,
    }
    return render(request, "catalog/withdraw.html", context=context)


@login_required
def TransferTransactionView(request):
    if request.method == "POST":
        form = TransferTransactionForm(request.user, request.POST)
        if form.is_valid():
            response_code = form.transfer_amount()
            if form.redirect:
                if response_code == 1:
                #not enough money in account
                    print("MONEY ERROR")
                    return HttpResponseRedirect(reverse('my-cards') )
                elif response_code == -1:
                #not enough money in atm
                    print("TARGET ERORR")
                    return HttpResponseRedirect(reverse('my-details') )
            else:
                print("Success")
                return HttpResponseRedirect(reverse('index') )

    form = TransferTransactionForm(request.user)
    context = {
         'form' : form,
    }
    return render(request, "catalog/transfer.html", context=context)
    

class BalanceInqView(LoginRequiredMixin,generic.ListView):
    model = Account
    template_name ='catalog/balance.html'
    paginate_by = 10

    def get_queryset(self):
        return Account.objects.filter(bank_user=self.request.user)
        
        

class ATMListView(PermissionRequiredMixin,generic.ListView):
    permission_required = 'catalog.atm.can_view_atm'
    model = ATM
    template_name ='catalog/atms.html'
    paginate_by = 10
    def get_queryset(self):
        return ATM.objects.all()


def UserCreateAccountView(request):
    if request.method == "POST":
        form = UserAccountCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("index")


    form = UserAccountCreationForm
    context = {
         'form' : form,
    }
    return render(request, "catalog/admin_create_account.html", context=context)
    
    
from django.contrib.auth.decorators import user_passes_test
@user_passes_test(lambda u: u.is_staff)
def AdminCreateAccountView(request):
    if request.method == "POST":
        form = AdminAccountCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("index")


    form = AdminAccountCreationForm
    context = {
         'form' : form,
    }
    return render(request, "catalog/admin_create_account.html", context=context)

locallibrary/catalog/templates/catalog/admin_create_account.html
{% extends "base_generic.html" %}

{% block content %}
  <form method="post">
    
    {{ form.as_p }}
    <input class="btn" type="submit" value="submit" />

  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/atm_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ atm.atm_number }}</h1>

  <p><strong>Address:</strong> {{ atm.address }}</p>

  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/atms.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>ATMS</h1>

    {% if atm_list %}
    <ul>

      {% for atm in atm_list %}
     
        <a href="{% url 'atm-detail' atm.pk %}">{{atm.atm_number}}</a> ({{ atm.address }})<br>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no cards on this account.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/balance.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Accounts:</h1>
    {% if account_list %}
    <ul>
      {% for account in account_list %}
        <a href="{% url 'account-detail' account.pk %}">Account #: {{account.account_number}}</a>  - {{ account.name }} {{ account.address }} - Current Balance is ${{ account.balance }}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>You have no account.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Card List</h1>
  {% if card_list %}
  <ul>
    {% for card in card_list %}
      <li>
        <a href="{{ card.get_absolute_url }}">{{ card.owner }}</a> ({{card.balance}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cards.</p>
  {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if card_list %}
    <ul>

      {% for card in card_list %}
     
        <a href="{% url 'card-detail' card.pk %}">{{card.owner}}</a> ({{ card.balance }})<br>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no cards on this account.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/card_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ card.owner }}</h1>

  <p><strong>Balance:</strong> {{ card.balance }}</p>

  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/transfer.html
{% extends "base_generic.html" %}

{% block content %}
  <form method="post">

    {{ form.as_p }}
    <input class="btn" type="submit" value="submit" />

  </form>

{% endblock %}

locallibrary/catalog/templates/catalog/transfer_card_user.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>From: {{ card_instance.owner }}</h1>
  <p>Balance: {{ card_instance.balance }}</p>
 
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}
<tr>
  <th><label for="id_transfer_amount">Transfer Amount:</label></th>
    <td>
      <ul class="errorlist">
        <li>Invalid Amount.</li>
      </ul>
      <input id="id_transfer_amount" name="transfer_amount" type="text" value="5" required>
      <br>
      <span class="helptext">Enter the amount to transfer.</span>
    </td>
</tr>

locallibrary/catalog/templates/catalog/withdraw.html
{% extends "base_generic.html" %}

{% block content %}
  <form method="post">

    {{ form.as_p }}
    <input class="btn" type="submit" value="submit" />

  </form>

{% endblock %}

locallibrary/catalog/templates/catalog/withdrawl.html
{% extends "base_generic.html" %}

{% block content %}
  <form method="post">
  {{ form.as_p }}

    <input class="btn" type="submit" value="submit" />

{% end block}